### ISSUE TITLE
Use JavaModuleType instead of custom ModuleType

### ISSUE THREAD

**Issue by jreznot** [oracle/gcn-intellij-tooling#3]
Hi, ModuleType concept is really outdated and we suggest using the standard one instead of GCNModuleType.

When code imported from Maven/Gradle the standard module type will be used and custom module type is not needed for anything in IDE

**Comment by MartinBalin** [comment]
Thank's for review. We will update this for next release of plugin.

**Comment by thurka** [comment]
Fixed in [GDK 1.1.0](https://plugins.jetbrains.com/plugin/24843-graal-dev-kit-for-micronaut)
